import { MigrationInterface, QueryRunner } from "typeorm";

export class CompleteInitialSchema1764837063938 implements MigrationInterface {
    name = 'CompleteInitialSchema1764837063938'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TYPE "public"."widget_types_category_enum" AS ENUM('alarm_widgets', 'analytics', 'cards', 'charts', 'control_widgets', 'date', 'gauges', 'gpio_widgets', 'input_widgets', 'maps', 'navigation', 'tables', 'weather', 'other')`);
        await queryRunner.query(`CREATE TABLE "widget_types" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "created_by" character varying, "updated_by" character varying, "name" character varying NOT NULL, "description" character varying, "category" "public"."widget_types_category_enum" NOT NULL DEFAULT 'other', "tenantId" character varying, "bundleFqn" character varying, "image" character varying, "iconUrl" text, "descriptor" jsonb NOT NULL, "settingsTemplate" jsonb, "tags" text, "system" boolean NOT NULL DEFAULT false, "deprecated" boolean NOT NULL DEFAULT false, "additionalInfo" jsonb, CONSTRAINT "UQ_077460328e63732c0d5bae1582a" UNIQUE ("name"), CONSTRAINT "PK_19a59ae7df24f4aaf5bba3d11b0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_077460328e63732c0d5bae1582" ON "widget_types" ("name") `);
        await queryRunner.query(`CREATE INDEX "IDX_e6f81a5fb5bd325c2316ec630b" ON "widget_types" ("category") `);
        await queryRunner.query(`CREATE INDEX "IDX_6d8daed2fa8cd92bb62d9b4255" ON "widget_types" ("tenantId") `);
        await queryRunner.query(`CREATE TYPE "public"."users_role_enum" AS ENUM('super_admin', 'tenant_admin', 'user')`);
        await queryRunner.query(`CREATE TYPE "public"."users_status_enum" AS ENUM('active', 'inactive', 'suspended')`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "created_by" character varying, "updated_by" character varying, "email" character varying NOT NULL, "password" character varying NOT NULL, "name" character varying NOT NULL, "phone" character varying, "role" "public"."users_role_enum" NOT NULL DEFAULT 'tenant_admin', "status" "public"."users_status_enum" NOT NULL DEFAULT 'active', "tenantId" character varying, "avatar" character varying, "lastLoginAt" TIMESTAMP, "emailVerified" boolean NOT NULL DEFAULT false, "emailVerificationToken" character varying, "passwordResetToken" character varying, "passwordResetExpires" TIMESTAMP, "preferences" jsonb, CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "UQ_a000cca60bcf04454e727699490" UNIQUE ("phone"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_97672ac88f789774dd47f7c8be" ON "users" ("email") `);
        await queryRunner.query(`CREATE TYPE "public"."two_factor_auth_method_enum" AS ENUM('authenticator', 'sms', 'email')`);
        await queryRunner.query(`CREATE TABLE "two_factor_auth" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "isEnabled" boolean NOT NULL DEFAULT false, "method" "public"."two_factor_auth_method_enum", "secret" character varying, "backupCodes" character varying, "phoneNumber" character varying, "phoneVerified" boolean NOT NULL DEFAULT false, "tempCode" character varying, "tempCodeExpiry" TIMESTAMP, "tempCodeAttempts" integer NOT NULL DEFAULT '0', "lastVerifiedAt" TIMESTAMP, "enabledAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_ceebe2fe995d01aeff8cb013f53" UNIQUE ("userId"), CONSTRAINT "REL_ceebe2fe995d01aeff8cb013f5" UNIQUE ("userId"), CONSTRAINT "PK_ac930594b4dbe3771cf16cd108d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ceebe2fe995d01aeff8cb013f5" ON "two_factor_auth" ("userId") `);
        await queryRunner.query(`CREATE TABLE "widget_bundles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "created_by" character varying, "updated_by" character varying, "title" character varying NOT NULL, "description" character varying, "tenantId" character varying, "image" character varying, "order" integer NOT NULL DEFAULT '0', "system" boolean NOT NULL DEFAULT false, "additionalInfo" jsonb, CONSTRAINT "UQ_1527965b6fd30f017a4f8affbc3" UNIQUE ("title"), CONSTRAINT "PK_d2d5dfbb15bbe6c45d863e509c9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_1527965b6fd30f017a4f8affbc" ON "widget_bundles" ("title") `);
        await queryRunner.query(`CREATE INDEX "IDX_fb71b94617998eb1e04f87d14d" ON "widget_bundles" ("tenantId") `);
        await queryRunner.query(`CREATE TYPE "public"."tenants_status_enum" AS ENUM('active', 'inactive', 'suspended')`);
        await queryRunner.query(`CREATE TABLE "tenants" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "created_by" character varying, "updated_by" character varying, "name" character varying NOT NULL, "title" character varying, "description" text, "email" character varying NOT NULL, "phone" character varying, "country" character varying, "state" character varying, "city" character varying, "address" character varying, "address2" character varying, "zip" character varying, "status" "public"."tenants_status_enum" NOT NULL DEFAULT 'active', "additionalInfo" jsonb, "configuration" jsonb NOT NULL DEFAULT '{}', "isolation_mode" character varying NOT NULL DEFAULT 'full', "tenant_admin_id" character varying, CONSTRAINT "UQ_32731f181236a46182a38c992a8" UNIQUE ("name"), CONSTRAINT "UQ_155c343439adc83ada6ee3f48be" UNIQUE ("email"), CONSTRAINT "PK_53be67a04681c66b87ee27c9321" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c59559e7872bc9726adef4669f" ON "tenants" ("status") `);
        await queryRunner.query(`CREATE TYPE "public"."solution_templates_category_enum" AS ENUM('smart_factory', 'smart_home', 'smart_building', 'smart_city', 'agriculture', 'healthcare', 'energy', 'logistics', 'retail', 'water', 'climate', 'education')`);
        await queryRunner.query(`CREATE TABLE "solution_templates" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "created_by" character varying, "updated_by" character varying, "name" character varying NOT NULL, "description" text NOT NULL, "category" "public"."solution_templates_category_enum" NOT NULL, "icon" character varying NOT NULL, "rating" numeric(3,2) NOT NULL DEFAULT '0', "installs" integer NOT NULL DEFAULT '0', "version" character varying NOT NULL DEFAULT '1.0.0', "last_updated" TIMESTAMP NOT NULL DEFAULT now(), "author" character varying NOT NULL, "features" jsonb NOT NULL DEFAULT '[]', "devices" integer NOT NULL DEFAULT '0', "dashboards" integer NOT NULL DEFAULT '0', "rules" integer NOT NULL DEFAULT '0', "tags" jsonb NOT NULL DEFAULT '[]', "is_premium" boolean NOT NULL DEFAULT false, "is_system" boolean NOT NULL DEFAULT true, "configuration" jsonb, "preview_image" character varying, "user_id" character varying, "tenant_id" character varying, CONSTRAINT "PK_7058a80eb84021b2bf189356918" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_70aae5590b03f9a19850ea429f" ON "solution_templates" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_a69a9338732daa77803f7ec450" ON "solution_templates" ("tenant_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_9cde4c8a4997ea781cdb5af3ec" ON "solution_templates" ("installs") `);
        await queryRunner.query(`CREATE INDEX "IDX_dc9a46466e27a2e969f760d083" ON "solution_templates" ("is_premium") `);
        await queryRunner.query(`CREATE INDEX "IDX_9c01268558440182b9888652e2" ON "solution_templates" ("category") `);
        await queryRunner.query(`CREATE TYPE "public"."shares_resourcetype_enum" AS ENUM('dashboard', 'device', 'asset', 'report', 'floor_plan')`);
        await queryRunner.query(`CREATE TYPE "public"."shares_sharetype_enum" AS ENUM('email', 'link')`);
        await queryRunner.query(`CREATE TYPE "public"."shares_accesslevel_enum" AS ENUM('view', 'edit', 'admin')`);
        await queryRunner.query(`CREATE TABLE "shares" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "created_by" character varying, "updated_by" character varying, "resourceType" "public"."shares_resourcetype_enum" NOT NULL, "resource_id" character varying NOT NULL, "shareType" "public"."shares_sharetype_enum" NOT NULL, "shared_with" character varying, "accessLevel" "public"."shares_accesslevel_enum" NOT NULL DEFAULT 'view', "token" character varying, "expires_at" TIMESTAMP, "views" integer NOT NULL DEFAULT '0', "is_public" boolean NOT NULL DEFAULT false, "shared_by" character varying NOT NULL, "user_id" character varying NOT NULL, "tenant_id" character varying, "metadata" jsonb, CONSTRAINT "UQ_f51f54e33eac0d4d7ada7422cf2" UNIQUE ("token"), CONSTRAINT "PK_b88473409066c43c2ccb1894a82" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f51f54e33eac0d4d7ada7422cf" ON "shares" ("token") `);
        await queryRunner.query(`CREATE INDEX "IDX_4c8ddcaa09bb1ac50dbbe8120c" ON "shares" ("shared_by") `);
        await queryRunner.query(`CREATE INDEX "IDX_a8aded2f90f448876f7fe63eab" ON "shares" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_9d4dac50fa63e9b6c5cccc14bd" ON "shares" ("tenant_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_2e688a3ebb477d286c7d3177de" ON "shares" ("shared_with") `);
        await queryRunner.query(`CREATE INDEX "IDX_fef990ce4738f381fbf08dd32b" ON "shares" ("shared_by", "resourceType") `);
        await queryRunner.query(`CREATE TYPE "public"."scripts_type_enum" AS ENUM('processing', 'filter', 'aggregation', 'validation', 'transformation')`);
        await queryRunner.query(`CREATE TABLE "scripts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "created_by" character varying, "updated_by" character varying, "name" character varying NOT NULL, "description" text, "language" character varying NOT NULL DEFAULT 'javascript', "type" "public"."scripts_type_enum" NOT NULL, "code" text NOT NULL, "version" character varying NOT NULL DEFAULT '1.0.0', "lines" integer NOT NULL DEFAULT '0', "last_modified" TIMESTAMP NOT NULL DEFAULT now(), "user_id" character varying NOT NULL, "tenant_id" character varying, CONSTRAINT "PK_399d1c469ffd6bac4e061e5fd8c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a1b16acf6c41ce6da45612c4a9" ON "scripts" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_e7e6185b1ee83be55370972627" ON "scripts" ("tenant_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_e956cdd092501b3c2dbdfcd174" ON "scripts" ("user_id", "type") `);
        await queryRunner.query(`CREATE TYPE "public"."schedules_type_enum" AS ENUM('report', 'backup', 'cleanup', 'export')`);
        await queryRunner.query(`CREATE TABLE "schedules" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "created_by" character varying, "updated_by" character varying, "name" character varying NOT NULL, "description" text, "type" "public"."schedules_type_enum" NOT NULL, "schedule" character varying NOT NULL, "enabled" boolean NOT NULL DEFAULT true, "configuration" jsonb NOT NULL, "last_run" TIMESTAMP, "next_run" TIMESTAMP NOT NULL, "execution_count" integer NOT NULL DEFAULT '0', "user_id" character varying NOT NULL, "tenant_id" character varying, CONSTRAINT "PK_7e33fc2ea755a5765e3564e66dd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_55e6651198104efea0b04568a8" ON "schedules" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_419857fc68975b6df572ad288d" ON "schedules" ("tenant_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_49ee2f991fefeedef715fa3b61" ON "schedules" ("user_id", "enabled") `);
        await queryRunner.query(`CREATE TYPE "public"."devices_type_enum" AS ENUM('sensor', 'actuator', 'gateway', 'controller', 'camera', 'tracker')`);
        await queryRunner.query(`CREATE TYPE "public"."devices_status_enum" AS ENUM('active', 'inactive', 'offline', 'maintenance', 'error')`);
        await queryRunner.query(`CREATE TYPE "public"."devices_connectiontype_enum" AS ENUM('wifi', 'ethernet', 'cellular', 'bluetooth', 'zigbee', 'lora')`);
        await queryRunner.query(`CREATE TABLE "devices" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "created_by" character varying, "updated_by" character varying, "deviceKey" character varying NOT NULL, "name" character varying NOT NULL, "deviceProfileId" character varying, "assetId" character varying, "description" text, "type" "public"."devices_type_enum" NOT NULL DEFAULT 'sensor', "status" "public"."devices_status_enum" NOT NULL DEFAULT 'inactive', "connectionType" "public"."devices_connectiontype_enum" NOT NULL DEFAULT 'wifi', "tenantId" character varying, "userId" uuid NOT NULL, "accessToken" character varying, "secretKey" character varying, "ipAddress" character varying, "macAddress" character varying, "firmwareVersion" character varying, "hardwareVersion" character varying, "latitude" numeric(10,7), "longitude" numeric(10,7), "location" character varying, "metadata" jsonb, "configuration" jsonb, "lastSeenAt" TIMESTAMP, "lastActivityAt" TIMESTAMP, "activatedAt" TIMESTAMP, "messageCount" integer NOT NULL DEFAULT '0', "errorCount" integer NOT NULL DEFAULT '0', "tags" jsonb, CONSTRAINT "UQ_c94785ca96e82f719c64dd1c243" UNIQUE ("deviceKey"), CONSTRAINT "PK_b1514758245c12daf43486dd1f0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_c94785ca96e82f719c64dd1c24" ON "devices" ("deviceKey") `);
        await queryRunner.query(`CREATE INDEX "IDX_e8a5d59f0ac3040395f159507c" ON "devices" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_6661d4424d9dfba678fa7d2408" ON "devices" ("tenantId", "status") `);
        await queryRunner.query(`CREATE TABLE "telemetry" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "created_by" character varying, "updated_by" character varying, "deviceId" uuid NOT NULL, "deviceKey" character varying NOT NULL, "timestamp" TIMESTAMP NOT NULL, "data" jsonb NOT NULL, "temperature" numeric(10,2), "humidity" numeric(10,2), "pressure" numeric(10,2), "latitude" numeric(10,7), "longitude" numeric(10,7), "batteryLevel" numeric(10,2), "signalStrength" integer, "metadata" jsonb, "tenantId" character varying, CONSTRAINT "PK_9b2e5d3feb141269a262aa75fe8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_45954b02214ca300fc4d21b3f4" ON "telemetry" ("timestamp") `);
        await queryRunner.query(`CREATE INDEX "IDX_873c3be6932c7c0f3e899e3380" ON "telemetry" ("deviceKey", "timestamp") `);
        await queryRunner.query(`CREATE INDEX "IDX_b342da06473346dbb895fb360e" ON "telemetry" ("deviceId", "timestamp") `);
        await queryRunner.query(`CREATE TYPE "public"."subscriptions_plan_enum" AS ENUM('free', 'starter', 'professional', 'enterprise')`);
        await queryRunner.query(`CREATE TYPE "public"."subscriptions_status_enum" AS ENUM('active', 'cancelled', 'expired', 'trial')`);
        await queryRunner.query(`CREATE TYPE "public"."subscriptions_billingperiod_enum" AS ENUM('monthly', 'yearly')`);
        await queryRunner.query(`CREATE TABLE "subscriptions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "created_by" character varying, "updated_by" character varying, "plan" "public"."subscriptions_plan_enum" NOT NULL DEFAULT 'free', "status" "public"."subscriptions_status_enum" NOT NULL DEFAULT 'active', "billingPeriod" "public"."subscriptions_billingperiod_enum" NOT NULL DEFAULT 'monthly', "price" numeric(10,2) NOT NULL DEFAULT '0', "limits" jsonb NOT NULL, "usage" jsonb NOT NULL, "features" jsonb, "next_billing_date" TIMESTAMP, "trial_ends_at" TIMESTAMP, "cancelled_at" TIMESTAMP, "user_id" character varying NOT NULL, "tenant_id" character varying, CONSTRAINT "PK_a87248d73155605cf782be9ee5e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_d0a95ef8a28188364c546eb65c" ON "subscriptions" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_f6ac03431c311ccb8bbd7d3af1" ON "subscriptions" ("tenant_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_1a15756e257e0eaf01edc85645" ON "subscriptions" ("user_id", "status") `);
        await queryRunner.query(`CREATE TYPE "public"."device_profiles_transporttype_enum" AS ENUM('mqtt', 'http', 'coap', 'lwm2m', 'snmp')`);
        await queryRunner.query(`CREATE TYPE "public"."device_profiles_provisiontype_enum" AS ENUM('disabled', 'allow_create_new', 'check_pre_provisioned')`);
        await queryRunner.query(`CREATE TABLE "device_profiles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "created_by" character varying, "updated_by" character varying, "name" character varying NOT NULL, "description" character varying, "tenantId" character varying, "default" boolean NOT NULL DEFAULT true, "type" character varying, "transportType" "public"."device_profiles_transporttype_enum" NOT NULL DEFAULT 'mqtt', "provisionType" "public"."device_profiles_provisiontype_enum" NOT NULL DEFAULT 'disabled', "transportConfiguration" jsonb, "profileData" jsonb, "telemetryConfig" jsonb, "attributesConfig" jsonb, "alarmRules" jsonb, "provisionConfiguration" jsonb, "firmwareConfiguration" jsonb, "defaultRuleChainId" character varying, "defaultDashboardId" character varying, "defaultQueueName" character varying, "image" character varying, "additionalInfo" jsonb, CONSTRAINT "UQ_28c2776f0cc5c2d8c5811636ac5" UNIQUE ("name"), CONSTRAINT "PK_67b7377a99bd9d934913f93fdf2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_28c2776f0cc5c2d8c5811636ac" ON "device_profiles" ("name") `);
        await queryRunner.query(`CREATE INDEX "IDX_0f211f0908cbde8eac247f8833" ON "device_profiles" ("tenantId") `);
        await queryRunner.query(`CREATE TABLE "asset_profiles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "created_by" character varying, "updated_by" character varying, "name" character varying NOT NULL, "description" character varying, "tenantId" character varying, "default" boolean NOT NULL DEFAULT false, "image" character varying, "attributesConfig" jsonb, "defaultDashboardId" character varying, "defaultRuleChainId" character varying, "defaultQueueName" character varying, "alarmRules" jsonb, "customFields" jsonb, "metadataSchema" jsonb, "additionalInfo" jsonb, CONSTRAINT "UQ_d8c8cfd143d41f513e003c05f86" UNIQUE ("name"), CONSTRAINT "PK_f6baccfb3cfc4e49a8d5b89c58c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_d8c8cfd143d41f513e003c05f8" ON "asset_profiles" ("name") `);
        await queryRunner.query(`CREATE INDEX "IDX_5d90ec68a82e6963eb2d4181b6" ON "asset_profiles" ("tenantId") `);
        await queryRunner.query(`CREATE TYPE "public"."payments_provider_enum" AS ENUM('moyasar', 'stripe')`);
        await queryRunner.query(`CREATE TYPE "public"."payments_status_enum" AS ENUM('pending', 'succeeded', 'failed', 'refunded', 'cancelled')`);
        await queryRunner.query(`CREATE TYPE "public"."payments_method_enum" AS ENUM('card', 'mada', 'apple_pay', 'stc_pay', 'other')`);
        await queryRunner.query(`CREATE TABLE "payments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "created_by" character varying, "updated_by" character varying, "user_id" character varying NOT NULL, "subscription_id" character varying NOT NULL, "payment_intent_id" character varying NOT NULL, "customer_id" character varying, "provider" "public"."payments_provider_enum" NOT NULL DEFAULT 'moyasar', "amount" numeric(10,2) NOT NULL, "currency" character varying(3) NOT NULL DEFAULT 'SAR', "status" "public"."payments_status_enum" NOT NULL DEFAULT 'pending', "method" "public"."payments_method_enum" NOT NULL DEFAULT 'card', "description" text, "metadata" jsonb, "paid_at" TIMESTAMP, "refunded_at" TIMESTAMP, "failure_reason" text, CONSTRAINT "UQ_0bd2a15bde4058590f0caea36b3" UNIQUE ("payment_intent_id"), CONSTRAINT "PK_197ab7af18c93fbb0c9b28b4a59" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_427785468fb7d2733f59e7d7d3" ON "payments" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_0bd2a15bde4058590f0caea36b" ON "payments" ("payment_intent_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_75848dfef07fd19027e08ca81d" ON "payments" ("subscription_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_c2a89b63635ae2b4cc76f17a08" ON "payments" ("user_id", "status") `);
        await queryRunner.query(`CREATE TYPE "public"."notifications_type_enum" AS ENUM('alarm', 'device', 'system', 'user', 'report')`);
        await queryRunner.query(`CREATE TYPE "public"."notifications_channel_enum" AS ENUM('email', 'sms', 'push', 'webhook', 'in_app')`);
        await queryRunner.query(`CREATE TYPE "public"."notifications_priority_enum" AS ENUM('low', 'normal', 'high', 'urgent')`);
        await queryRunner.query(`CREATE TYPE "public"."notifications_status_enum" AS ENUM('pending', 'sent', 'delivered', 'failed', 'read')`);
        await queryRunner.query(`CREATE TABLE "notifications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "created_by" character varying, "updated_by" character varying, "userId" uuid NOT NULL, "type" "public"."notifications_type_enum" NOT NULL DEFAULT 'system', "channel" "public"."notifications_channel_enum" NOT NULL, "priority" "public"."notifications_priority_enum" NOT NULL DEFAULT 'normal', "status" "public"."notifications_status_enum" NOT NULL DEFAULT 'pending', "title" character varying NOT NULL, "message" text NOT NULL, "htmlContent" text, "relatedEntityType" character varying, "relatedEntityId" character varying, "action" jsonb, "metadata" jsonb, "recipientEmail" character varying, "recipientPhone" character varying, "recipientDeviceToken" character varying, "webhookUrl" character varying, "isRead" boolean NOT NULL DEFAULT false, "readAt" TIMESTAMP, "sentAt" TIMESTAMP, "deliveredAt" TIMESTAMP, "failedAt" TIMESTAMP, "errorMessage" text, "retryCount" integer NOT NULL DEFAULT '0', "maxRetries" integer NOT NULL DEFAULT '3', "scheduledFor" TIMESTAMP, "expiresAt" TIMESTAMP, CONSTRAINT "PK_6a72c3c0f683f6462415e653c3a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_7dd11c7db3072f87516bdca486" ON "notifications" ("type", "created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_5340fc241f57310d243e5ab20b" ON "notifications" ("userId", "isRead") `);
        await queryRunner.query(`CREATE INDEX "IDX_78207b2dc2b0d717649e89d3fc" ON "notifications" ("userId", "status") `);
        await queryRunner.query(`CREATE TYPE "public"."nodes_type_enum" AS ENUM('filter', 'enrichment', 'transformation', 'action', 'external', 'flow')`);
        await queryRunner.query(`CREATE TABLE "nodes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "created_by" character varying, "updated_by" character varying, "name" character varying NOT NULL, "description" text, "type" "public"."nodes_type_enum" NOT NULL, "rule_chain_id" character varying, "configuration" jsonb NOT NULL, "position" jsonb NOT NULL DEFAULT '{}', "enabled" boolean NOT NULL DEFAULT true, "debug_mode" boolean NOT NULL DEFAULT false, "additionalInfo" jsonb NOT NULL DEFAULT '[]', "user_id" character varying NOT NULL, "tenant_id" character varying, CONSTRAINT "PK_682d6427523a0fa43d062ea03ee" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_6269763dc8cc4e61f55c2e9782" ON "nodes" ("rule_chain_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_a8e9d4a017a4c4ba2be64468e8" ON "nodes" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_c21681c2db857b56e9382a3b2e" ON "nodes" ("tenant_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_bacf4193653cb8a31012a6de9d" ON "nodes" ("type") `);
        await queryRunner.query(`CREATE TYPE "public"."integrations_type_enum" AS ENUM('cloud', 'webhook', 'mqtt', 'notification')`);
        await queryRunner.query(`CREATE TYPE "public"."integrations_status_enum" AS ENUM('active', 'inactive', 'error')`);
        await queryRunner.query(`CREATE TABLE "integrations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "created_by" character varying, "updated_by" character varying, "name" character varying NOT NULL, "type" "public"."integrations_type_enum" NOT NULL, "protocol" character varying NOT NULL, "description" text, "status" "public"."integrations_status_enum" NOT NULL DEFAULT 'inactive', "enabled" boolean NOT NULL DEFAULT true, "configuration" jsonb NOT NULL, "messages_processed" integer NOT NULL DEFAULT '0', "last_activity" TIMESTAMP, "user_id" character varying NOT NULL, "tenant_id" character varying, CONSTRAINT "PK_9adcdc6d6f3922535361ce641e8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_75c40bb6e2430dd4b7a0b109d0" ON "integrations" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_d27dfc19be4aa3c1a45655d5a1" ON "integrations" ("tenant_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_589b255b725d109cb1e9ab13ea" ON "integrations" ("user_id", "status") `);
        await queryRunner.query(`CREATE TABLE "images" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "created_by" character varying, "updated_by" character varying, "name" character varying NOT NULL, "original_name" character varying NOT NULL, "mime_type" character varying NOT NULL, "size" bigint NOT NULL, "url" character varying NOT NULL, "path" character varying NOT NULL, "dimensions" jsonb, "uploaded_by" character varying NOT NULL, "user_id" character varying NOT NULL, "tenant_id" character varying, CONSTRAINT "PK_1fe148074c6a1a91b63cb9ee3c9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_decdf86f650fb765dac7bd091a" ON "images" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_b20f6c858a0fda5edf2e815832" ON "images" ("tenant_id") `);
        await queryRunner.query(`CREATE TYPE "public"."floor_plans_status_enum" AS ENUM('active', 'draft', 'archived')`);
        await queryRunner.query(`CREATE TABLE "floor_plans" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "created_by" character varying, "updated_by" character varying, "name" character varying NOT NULL, "building" character varying NOT NULL, "floor" character varying NOT NULL, "image_url" character varying, "category" character varying NOT NULL, "status" "public"."floor_plans_status_enum" NOT NULL DEFAULT 'draft', "dimensions" jsonb NOT NULL, "scale" character varying, "devices" jsonb NOT NULL DEFAULT '[]', "zones" jsonb NOT NULL DEFAULT '[]', "user_id" character varying NOT NULL, "tenant_id" character varying, CONSTRAINT "PK_4243d68fe3bfa6a38a2cccd5e9f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_71a32779f1bff3b131e1107835" ON "floor_plans" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_144447b168fb9ceda44c4c6d9d" ON "floor_plans" ("tenant_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_9fdb17c6b3cddc6c919bbb1a31" ON "floor_plans" ("user_id", "status") `);
        await queryRunner.query(`CREATE TYPE "public"."email_templates_type_enum" AS ENUM('verification', 'welcome', 'password_reset', 'password_changed', 'account_locked', 'two_factor_code', 'alert_notification', 'device_offline', 'subscription_expiring', 'custom')`);
        await queryRunner.query(`CREATE TABLE "email_templates" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "type" "public"."email_templates_type_enum" NOT NULL, "name" character varying NOT NULL, "subject" character varying NOT NULL, "htmlTemplate" text NOT NULL, "textTemplate" text NOT NULL, "variables" jsonb, "isActive" boolean NOT NULL DEFAULT true, "description" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_ed00bc5c34216c3969792984c1f" UNIQUE ("type"), CONSTRAINT "PK_06c564c515d8cdb40b6f3bfbbb4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."edge_instances_status_enum" AS ENUM('online', 'offline', 'syncing', 'error')`);
        await queryRunner.query(`CREATE TABLE "edge_instances" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "created_by" character varying, "updated_by" character varying, "name" character varying NOT NULL, "location" character varying NOT NULL, "status" "public"."edge_instances_status_enum" NOT NULL DEFAULT 'offline', "version" character varying NOT NULL, "ip_address" character varying NOT NULL, "last_seen" TIMESTAMP, "devices" integer NOT NULL DEFAULT '0', "metrics" jsonb NOT NULL, "data_sync" jsonb NOT NULL, "user_id" character varying NOT NULL, "tenant_id" character varying, CONSTRAINT "PK_2e9e289cf88f17378426831fd9c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f7d63ac9ad32550569fad7cb5f" ON "edge_instances" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_8471fcf39a1e128b52c88e0c99" ON "edge_instances" ("user_id", "status") `);
        await queryRunner.query(`CREATE TYPE "public"."device_credentials_credentialstype_enum" AS ENUM('ACCESS_TOKEN', 'MQTT_BASIC', 'X509_CERTIFICATE')`);
        await queryRunner.query(`CREATE TABLE "device_credentials" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "device_id" uuid NOT NULL, "credentialsType" "public"."device_credentials_credentialstype_enum" NOT NULL DEFAULT 'ACCESS_TOKEN', "credentials_id" character varying NOT NULL, "credentials_value" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_1d32fea307059af07a35e246bf3" UNIQUE ("credentials_id"), CONSTRAINT "PK_96678b2954bc2c8d4d5be68f011" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_838147fb05afc59ee78c3788fd" ON "device_credentials" ("device_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_1d32fea307059af07a35e246bf" ON "device_credentials" ("credentials_id") `);
        await queryRunner.query(`CREATE TABLE "device_command" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "deviceId" uuid NOT NULL, "userId" uuid NOT NULL, "tenantId" character varying NOT NULL, "commandType" character varying NOT NULL, "params" jsonb NOT NULL DEFAULT '{}', "priority" character varying NOT NULL DEFAULT 'NORMAL', "status" character varying NOT NULL DEFAULT 'PENDING', "statusMessage" text, "timeout" integer NOT NULL DEFAULT '30000', "retries" integer NOT NULL DEFAULT '3', "scheduledFor" TIMESTAMP, "deliveredAt" TIMESTAMP, "completedAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "metadata" jsonb DEFAULT '{}', CONSTRAINT "PK_f7ee291a5e600aedcffcedbd482" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."dashboards_visibility_enum" AS ENUM('private', 'shared', 'public')`);
        await queryRunner.query(`CREATE TABLE "dashboards" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "created_by" character varying, "updated_by" character varying, "name" character varying NOT NULL, "description" text, "visibility" "public"."dashboards_visibility_enum" NOT NULL DEFAULT 'private', "userId" uuid NOT NULL, "widgets" jsonb NOT NULL DEFAULT '[]', "layout" jsonb, "settings" jsonb, "filters" jsonb, "isDefault" boolean NOT NULL DEFAULT false, "isFavorite" boolean NOT NULL DEFAULT false, "sharedWith" jsonb, "viewCount" integer NOT NULL DEFAULT '0', "lastViewedAt" TIMESTAMP, "tags" jsonb, CONSTRAINT "PK_1b4b4bc346118e0d335f16c5344" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."automations_status_enum" AS ENUM('active', 'inactive', 'error')`);
        await queryRunner.query(`CREATE TABLE "automations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "created_by" character varying, "updated_by" character varying, "name" character varying NOT NULL, "description" text, "enabled" boolean NOT NULL DEFAULT true, "trigger" jsonb NOT NULL, "action" jsonb NOT NULL, "execution_count" integer NOT NULL DEFAULT '0', "last_triggered" TIMESTAMP, "status" "public"."automations_status_enum" NOT NULL DEFAULT 'inactive', "user_id" character varying NOT NULL, "tenant_id" character varying, CONSTRAINT "PK_34c2cc382fc780ea36f7c478192" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_9daee1f9161543c666c37cbedb" ON "automations" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_4a54b39fd853076ba90d69b956" ON "automations" ("tenant_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_827d0a6889f8256c5d1a79927e" ON "automations" ("user_id", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_293e5e42043bc41a1892d56279" ON "automations" ("user_id", "enabled") `);
        await queryRunner.query(`CREATE TYPE "public"."audit_logs_action_enum" AS ENUM('create', 'read', 'update', 'delete', 'login', 'logout', 'password_change', 'password_reset', 'email_verify', 'status_change', 'role_change', 'device_connect', 'device_disconnect', 'alarm_trigger', 'alarm_acknowledge', 'notification_sent', 'file_upload', 'file_delete', 'settings_change', 'api_key_create', 'api_key_revoke')`);
        await queryRunner.query(`CREATE TYPE "public"."audit_logs_entitytype_enum" AS ENUM('user', 'device', 'alarm', 'notification', 'dashboard', 'telemetry', 'rule', 'settings', 'file', 'api_key')`);
        await queryRunner.query(`CREATE TYPE "public"."audit_logs_severity_enum" AS ENUM('info', 'warning', 'error', 'critical')`);
        await queryRunner.query(`CREATE TABLE "audit_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "created_by" character varying, "updated_by" character varying, "userId" character varying, "userName" character varying, "userEmail" character varying, "action" "public"."audit_logs_action_enum" NOT NULL, "entityType" "public"."audit_logs_entitytype_enum" NOT NULL, "entityId" character varying, "entityName" character varying, "description" text, "metadata" jsonb, "changes" jsonb, "ipAddress" character varying, "userAgent" character varying, "severity" "public"."audit_logs_severity_enum" NOT NULL DEFAULT 'info', "timestamp" TIMESTAMP NOT NULL DEFAULT now(), "success" boolean NOT NULL DEFAULT true, "errorMessage" text, "tenantId" character varying, CONSTRAINT "PK_1bb179d048bbc581caa3b013439" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_cfa83f61e4d27a87fcae1e025a" ON "audit_logs" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_cee5459245f652b75eb2759b4c" ON "audit_logs" ("action") `);
        await queryRunner.query(`CREATE INDEX "IDX_01993ae76b293d3b866cc3a125" ON "audit_logs" ("entityType") `);
        await queryRunner.query(`CREATE INDEX "IDX_f23279fad63453147a8efb46cf" ON "audit_logs" ("entityId") `);
        await queryRunner.query(`CREATE INDEX "IDX_88dcc148d532384790ab874c3d" ON "audit_logs" ("timestamp") `);
        await queryRunner.query(`CREATE INDEX "IDX_17b613a55b287678b6f26ab8b2" ON "audit_logs" ("action", "timestamp") `);
        await queryRunner.query(`CREATE INDEX "IDX_13c69424c440a0e765053feb4b" ON "audit_logs" ("entityType", "entityId") `);
        await queryRunner.query(`CREATE INDEX "IDX_65bf0f1c91acea1b3dcf5b98f1" ON "audit_logs" ("userId", "timestamp") `);
        await queryRunner.query(`CREATE TABLE "token_blacklist" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "token" text NOT NULL, "userId" uuid NOT NULL, "expiresAt" TIMESTAMP NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_8c2ca80e62a4a178870aa9e7a0e" UNIQUE ("token"), CONSTRAINT "PK_3e37528d03f0bd5335874afa48d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_1cebed586d3a7c46f3f9b76cf1" ON "token_blacklist" ("expiresAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_8c2ca80e62a4a178870aa9e7a0" ON "token_blacklist" ("token") `);
        await queryRunner.query(`CREATE TABLE "refresh_tokens" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "created_by" character varying, "updated_by" character varying, "token" character varying NOT NULL, "userId" uuid NOT NULL, "expiresAt" TIMESTAMP NOT NULL, "isRevoked" boolean NOT NULL DEFAULT false, "deviceInfo" character varying, "ipAddress" character varying, "userAgent" character varying, CONSTRAINT "UQ_4542dd2f38a61354a040ba9fd57" UNIQUE ("token"), CONSTRAINT "PK_7d8bee0204106019488c4c50ffa" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_4542dd2f38a61354a040ba9fd5" ON "refresh_tokens" ("token") `);
        await queryRunner.query(`CREATE TYPE "public"."oauth_accounts_provider_enum" AS ENUM('google', 'github', 'apple')`);
        await queryRunner.query(`CREATE TABLE "oauth_accounts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "created_by" character varying, "updated_by" character varying, "userId" uuid NOT NULL, "provider" "public"."oauth_accounts_provider_enum" NOT NULL, "providerId" character varying NOT NULL, "providerEmail" character varying, "accessToken" text, "refreshToken" text, "tokenExpiresAt" TIMESTAMP, "profile" jsonb, CONSTRAINT "PK_710a81523f515b78f894e33bb10" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_c2d536981fc2eade0e01e774d0" ON "oauth_accounts" ("provider", "providerId") `);
        await queryRunner.query(`CREATE TYPE "public"."attributes_scope_enum" AS ENUM('server', 'shared', 'client')`);
        await queryRunner.query(`CREATE TYPE "public"."attributes_datatype_enum" AS ENUM('string', 'number', 'boolean', 'json')`);
        await queryRunner.query(`CREATE TABLE "attributes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "created_by" character varying, "updated_by" character varying, "entity_type" character varying NOT NULL, "entity_id" character varying NOT NULL, "attribute_key" character varying NOT NULL, "scope" "public"."attributes_scope_enum" NOT NULL DEFAULT 'server', "dataType" "public"."attributes_datatype_enum" NOT NULL, "string_value" character varying, "number_value" numeric(20,6), "boolean_value" boolean, "json_value" jsonb, "last_update_ts" bigint NOT NULL, "user_id" character varying NOT NULL, "tenant_id" character varying, CONSTRAINT "PK_32216e2e61830211d3a5d7fa72c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e8ffbe7af393d91964680e5e7d" ON "attributes" ("entity_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_e153bb592c635b8751c4b657cb" ON "attributes" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_8df16cd370327023ca61899161" ON "attributes" ("tenant_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_6e09de3e945f9442844376dbf9" ON "attributes" ("attribute_key") `);
        await queryRunner.query(`CREATE INDEX "IDX_a43f32e40e2896e08c0da983ae" ON "attributes" ("entity_type", "entity_id", "scope") `);
        await queryRunner.query(`CREATE INDEX "IDX_ad85a949fb50b73e1f43b54daf" ON "attributes" ("entity_type", "entity_id") `);
        await queryRunner.query(`CREATE TYPE "public"."assets_type_enum" AS ENUM('building', 'floor', 'room', 'vehicle', 'equipment', 'infrastructure', 'other')`);
        await queryRunner.query(`CREATE TABLE "assets" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "created_by" character varying, "updated_by" character varying, "name" character varying NOT NULL, "label" character varying, "type" "public"."assets_type_enum" NOT NULL DEFAULT 'other', "tenantId" character varying, "customerId" character varying, "assetProfileId" character varying, "parentAssetId" uuid, "additionalInfo" jsonb, "location" jsonb, "attributes" jsonb, "tags" text, "description" character varying, "imageUrl" character varying, "active" boolean NOT NULL DEFAULT true, "ownerId" character varying, "ownerName" character varying, "maintenance" jsonb, CONSTRAINT "PK_da96729a8b113377cfb6a62439c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_6e8f4260f76fb9432482252abf" ON "assets" ("tenantId") `);
        await queryRunner.query(`CREATE INDEX "IDX_8df38dd10f617eb58af42c6bd0" ON "assets" ("customerId") `);
        await queryRunner.query(`CREATE INDEX "IDX_18b0248f3d7522140aa7760f8b" ON "assets" ("assetProfileId") `);
        await queryRunner.query(`CREATE INDEX "IDX_9319c6007a6741777b457490ac" ON "assets" ("parentAssetId") `);
        await queryRunner.query(`CREATE TABLE "api_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "created_by" character varying, "updated_by" character varying, "method" character varying NOT NULL, "endpoint" character varying NOT NULL, "status_code" integer NOT NULL, "response_time" integer NOT NULL, "user_id" character varying, "tenant_id" character varying, "ip" character varying NOT NULL, "user_agent" character varying, "request" jsonb, "response" jsonb, "error_message" text, "timestamp" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_ea3f2ad34a2921407593ff4425b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ebafe127b747fe9c15a2c3ef52" ON "api_logs" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_9dad5625656b37dfd6e57324ec" ON "api_logs" ("tenant_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_4eb0f23e0693ad4fec007956db" ON "api_logs" ("status_code") `);
        await queryRunner.query(`CREATE INDEX "IDX_467c3bbe089f528721a756398d" ON "api_logs" ("endpoint") `);
        await queryRunner.query(`CREATE INDEX "IDX_7d6ec96642886533aa80925bfe" ON "api_logs" ("user_id", "timestamp") `);
        await queryRunner.query(`CREATE TYPE "public"."analytics_type_enum" AS ENUM('device_usage', 'telemetry_stats', 'alarm_frequency', 'user_activity', 'system_performance')`);
        await queryRunner.query(`CREATE TYPE "public"."analytics_period_enum" AS ENUM('hourly', 'daily', 'weekly', 'monthly')`);
        await queryRunner.query(`CREATE TABLE "analytics" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "created_by" character varying, "updated_by" character varying, "type" "public"."analytics_type_enum" NOT NULL, "period" "public"."analytics_period_enum" NOT NULL, "entityId" character varying, "entityType" character varying, "metrics" jsonb NOT NULL, "timestamp" TIMESTAMP NOT NULL, "tenantId" character varying, CONSTRAINT "PK_3c96dcbf1e4c57ea9e0c3144bff" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_2de1d3124c07ed32d4c9e0c2a6" ON "analytics" ("type") `);
        await queryRunner.query(`CREATE INDEX "IDX_7ed6d4b0e2e5467752cb14a44d" ON "analytics" ("entityId") `);
        await queryRunner.query(`CREATE INDEX "IDX_e536ace05b3ada403b32fa6d95" ON "analytics" ("timestamp") `);
        await queryRunner.query(`CREATE INDEX "IDX_b8fdc0c90adb95a3b05f6c2b6e" ON "analytics" ("entityId", "timestamp") `);
        await queryRunner.query(`CREATE INDEX "IDX_c39551f1426678d8ee28d09738" ON "analytics" ("type", "period", "timestamp") `);
        await queryRunner.query(`CREATE TYPE "public"."alarms_severity_enum" AS ENUM('info', 'warning', 'error', 'critical')`);
        await queryRunner.query(`CREATE TYPE "public"."alarms_status_enum" AS ENUM('active', 'acknowledged', 'cleared', 'resolved')`);
        await queryRunner.query(`CREATE TABLE "alarms" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "created_by" character varying, "updated_by" character varying, "name" character varying NOT NULL, "description" text, "severity" "public"."alarms_severity_enum" NOT NULL DEFAULT 'warning', "status" "public"."alarms_status_enum" NOT NULL DEFAULT 'active', "userId" uuid NOT NULL, "deviceId" uuid, "rule" jsonb NOT NULL, "currentValue" numeric(10,2), "message" text, "triggeredAt" TIMESTAMP, "acknowledgedAt" TIMESTAMP, "acknowledgedBy" character varying, "clearedAt" TIMESTAMP, "resolvedAt" TIMESTAMP, "resolvedBy" character varying, "resolutionNote" text, "isEnabled" boolean NOT NULL DEFAULT true, "autoClear" boolean NOT NULL DEFAULT true, "notifications" jsonb, "recipients" jsonb, "triggerCount" integer NOT NULL DEFAULT '0', "lastTriggeredAt" TIMESTAMP, "metadata" jsonb, "tags" jsonb, CONSTRAINT "PK_b776da486fb19d38b4f7777a6da" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_383453ca32ddeee9919898503d" ON "alarms" ("status", "severity") `);
        await queryRunner.query(`CREATE INDEX "IDX_42ef77b28dbec653636d9990d8" ON "alarms" ("userId", "severity") `);
        await queryRunner.query(`CREATE INDEX "IDX_cc202a34e13245c4c959bec7d8" ON "alarms" ("deviceId", "status") `);
        await queryRunner.query(`ALTER TABLE "two_factor_auth" ADD CONSTRAINT "FK_ceebe2fe995d01aeff8cb013f53" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "devices" ADD CONSTRAINT "FK_e8a5d59f0ac3040395f159507c6" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "telemetry" ADD CONSTRAINT "FK_0b39d2e21a7571edfee60339dff" FOREIGN KEY ("deviceId") REFERENCES "devices"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_692a909ee0fa9383e7859f9b406" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "device_credentials" ADD CONSTRAINT "FK_838147fb05afc59ee78c3788fd3" FOREIGN KEY ("device_id") REFERENCES "devices"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "device_command" ADD CONSTRAINT "FK_0f003545226d6cf6a4520c14c1f" FOREIGN KEY ("deviceId") REFERENCES "devices"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "device_command" ADD CONSTRAINT "FK_4f0c27f7ec30d52dad616dad4b0" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "dashboards" ADD CONSTRAINT "FK_f82f5f19534c72468280610ac64" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" ADD CONSTRAINT "FK_610102b60fea1455310ccd299de" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "oauth_accounts" ADD CONSTRAINT "FK_4c22f13249ce02f89dc6d226e9c" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "assets" ADD CONSTRAINT "FK_9319c6007a6741777b457490ace" FOREIGN KEY ("parentAssetId") REFERENCES "assets"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "alarms" ADD CONSTRAINT "FK_80dcfeb5d83f739b2e09a88a561" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "alarms" ADD CONSTRAINT "FK_c78f23725662dfbbf52f5cec247" FOREIGN KEY ("deviceId") REFERENCES "devices"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "alarms" DROP CONSTRAINT "FK_c78f23725662dfbbf52f5cec247"`);
        await queryRunner.query(`ALTER TABLE "alarms" DROP CONSTRAINT "FK_80dcfeb5d83f739b2e09a88a561"`);
        await queryRunner.query(`ALTER TABLE "assets" DROP CONSTRAINT "FK_9319c6007a6741777b457490ace"`);
        await queryRunner.query(`ALTER TABLE "oauth_accounts" DROP CONSTRAINT "FK_4c22f13249ce02f89dc6d226e9c"`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" DROP CONSTRAINT "FK_610102b60fea1455310ccd299de"`);
        await queryRunner.query(`ALTER TABLE "dashboards" DROP CONSTRAINT "FK_f82f5f19534c72468280610ac64"`);
        await queryRunner.query(`ALTER TABLE "device_command" DROP CONSTRAINT "FK_4f0c27f7ec30d52dad616dad4b0"`);
        await queryRunner.query(`ALTER TABLE "device_command" DROP CONSTRAINT "FK_0f003545226d6cf6a4520c14c1f"`);
        await queryRunner.query(`ALTER TABLE "device_credentials" DROP CONSTRAINT "FK_838147fb05afc59ee78c3788fd3"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_692a909ee0fa9383e7859f9b406"`);
        await queryRunner.query(`ALTER TABLE "telemetry" DROP CONSTRAINT "FK_0b39d2e21a7571edfee60339dff"`);
        await queryRunner.query(`ALTER TABLE "devices" DROP CONSTRAINT "FK_e8a5d59f0ac3040395f159507c6"`);
        await queryRunner.query(`ALTER TABLE "two_factor_auth" DROP CONSTRAINT "FK_ceebe2fe995d01aeff8cb013f53"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cc202a34e13245c4c959bec7d8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_42ef77b28dbec653636d9990d8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_383453ca32ddeee9919898503d"`);
        await queryRunner.query(`DROP TABLE "alarms"`);
        await queryRunner.query(`DROP TYPE "public"."alarms_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."alarms_severity_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c39551f1426678d8ee28d09738"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b8fdc0c90adb95a3b05f6c2b6e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e536ace05b3ada403b32fa6d95"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7ed6d4b0e2e5467752cb14a44d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2de1d3124c07ed32d4c9e0c2a6"`);
        await queryRunner.query(`DROP TABLE "analytics"`);
        await queryRunner.query(`DROP TYPE "public"."analytics_period_enum"`);
        await queryRunner.query(`DROP TYPE "public"."analytics_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7d6ec96642886533aa80925bfe"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_467c3bbe089f528721a756398d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4eb0f23e0693ad4fec007956db"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9dad5625656b37dfd6e57324ec"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ebafe127b747fe9c15a2c3ef52"`);
        await queryRunner.query(`DROP TABLE "api_logs"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9319c6007a6741777b457490ac"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_18b0248f3d7522140aa7760f8b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8df38dd10f617eb58af42c6bd0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6e8f4260f76fb9432482252abf"`);
        await queryRunner.query(`DROP TABLE "assets"`);
        await queryRunner.query(`DROP TYPE "public"."assets_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ad85a949fb50b73e1f43b54daf"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a43f32e40e2896e08c0da983ae"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6e09de3e945f9442844376dbf9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8df16cd370327023ca61899161"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e153bb592c635b8751c4b657cb"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e8ffbe7af393d91964680e5e7d"`);
        await queryRunner.query(`DROP TABLE "attributes"`);
        await queryRunner.query(`DROP TYPE "public"."attributes_datatype_enum"`);
        await queryRunner.query(`DROP TYPE "public"."attributes_scope_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c2d536981fc2eade0e01e774d0"`);
        await queryRunner.query(`DROP TABLE "oauth_accounts"`);
        await queryRunner.query(`DROP TYPE "public"."oauth_accounts_provider_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4542dd2f38a61354a040ba9fd5"`);
        await queryRunner.query(`DROP TABLE "refresh_tokens"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8c2ca80e62a4a178870aa9e7a0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1cebed586d3a7c46f3f9b76cf1"`);
        await queryRunner.query(`DROP TABLE "token_blacklist"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_65bf0f1c91acea1b3dcf5b98f1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_13c69424c440a0e765053feb4b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_17b613a55b287678b6f26ab8b2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_88dcc148d532384790ab874c3d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f23279fad63453147a8efb46cf"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_01993ae76b293d3b866cc3a125"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cee5459245f652b75eb2759b4c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cfa83f61e4d27a87fcae1e025a"`);
        await queryRunner.query(`DROP TABLE "audit_logs"`);
        await queryRunner.query(`DROP TYPE "public"."audit_logs_severity_enum"`);
        await queryRunner.query(`DROP TYPE "public"."audit_logs_entitytype_enum"`);
        await queryRunner.query(`DROP TYPE "public"."audit_logs_action_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_293e5e42043bc41a1892d56279"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_827d0a6889f8256c5d1a79927e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4a54b39fd853076ba90d69b956"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9daee1f9161543c666c37cbedb"`);
        await queryRunner.query(`DROP TABLE "automations"`);
        await queryRunner.query(`DROP TYPE "public"."automations_status_enum"`);
        await queryRunner.query(`DROP TABLE "dashboards"`);
        await queryRunner.query(`DROP TYPE "public"."dashboards_visibility_enum"`);
        await queryRunner.query(`DROP TABLE "device_command"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1d32fea307059af07a35e246bf"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_838147fb05afc59ee78c3788fd"`);
        await queryRunner.query(`DROP TABLE "device_credentials"`);
        await queryRunner.query(`DROP TYPE "public"."device_credentials_credentialstype_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8471fcf39a1e128b52c88e0c99"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f7d63ac9ad32550569fad7cb5f"`);
        await queryRunner.query(`DROP TABLE "edge_instances"`);
        await queryRunner.query(`DROP TYPE "public"."edge_instances_status_enum"`);
        await queryRunner.query(`DROP TABLE "email_templates"`);
        await queryRunner.query(`DROP TYPE "public"."email_templates_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9fdb17c6b3cddc6c919bbb1a31"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_144447b168fb9ceda44c4c6d9d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_71a32779f1bff3b131e1107835"`);
        await queryRunner.query(`DROP TABLE "floor_plans"`);
        await queryRunner.query(`DROP TYPE "public"."floor_plans_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b20f6c858a0fda5edf2e815832"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_decdf86f650fb765dac7bd091a"`);
        await queryRunner.query(`DROP TABLE "images"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_589b255b725d109cb1e9ab13ea"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d27dfc19be4aa3c1a45655d5a1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_75c40bb6e2430dd4b7a0b109d0"`);
        await queryRunner.query(`DROP TABLE "integrations"`);
        await queryRunner.query(`DROP TYPE "public"."integrations_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."integrations_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bacf4193653cb8a31012a6de9d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c21681c2db857b56e9382a3b2e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a8e9d4a017a4c4ba2be64468e8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6269763dc8cc4e61f55c2e9782"`);
        await queryRunner.query(`DROP TABLE "nodes"`);
        await queryRunner.query(`DROP TYPE "public"."nodes_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_78207b2dc2b0d717649e89d3fc"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5340fc241f57310d243e5ab20b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7dd11c7db3072f87516bdca486"`);
        await queryRunner.query(`DROP TABLE "notifications"`);
        await queryRunner.query(`DROP TYPE "public"."notifications_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."notifications_priority_enum"`);
        await queryRunner.query(`DROP TYPE "public"."notifications_channel_enum"`);
        await queryRunner.query(`DROP TYPE "public"."notifications_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c2a89b63635ae2b4cc76f17a08"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_75848dfef07fd19027e08ca81d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0bd2a15bde4058590f0caea36b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_427785468fb7d2733f59e7d7d3"`);
        await queryRunner.query(`DROP TABLE "payments"`);
        await queryRunner.query(`DROP TYPE "public"."payments_method_enum"`);
        await queryRunner.query(`DROP TYPE "public"."payments_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."payments_provider_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5d90ec68a82e6963eb2d4181b6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d8c8cfd143d41f513e003c05f8"`);
        await queryRunner.query(`DROP TABLE "asset_profiles"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0f211f0908cbde8eac247f8833"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_28c2776f0cc5c2d8c5811636ac"`);
        await queryRunner.query(`DROP TABLE "device_profiles"`);
        await queryRunner.query(`DROP TYPE "public"."device_profiles_provisiontype_enum"`);
        await queryRunner.query(`DROP TYPE "public"."device_profiles_transporttype_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1a15756e257e0eaf01edc85645"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f6ac03431c311ccb8bbd7d3af1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d0a95ef8a28188364c546eb65c"`);
        await queryRunner.query(`DROP TABLE "subscriptions"`);
        await queryRunner.query(`DROP TYPE "public"."subscriptions_billingperiod_enum"`);
        await queryRunner.query(`DROP TYPE "public"."subscriptions_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."subscriptions_plan_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b342da06473346dbb895fb360e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_873c3be6932c7c0f3e899e3380"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_45954b02214ca300fc4d21b3f4"`);
        await queryRunner.query(`DROP TABLE "telemetry"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6661d4424d9dfba678fa7d2408"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e8a5d59f0ac3040395f159507c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c94785ca96e82f719c64dd1c24"`);
        await queryRunner.query(`DROP TABLE "devices"`);
        await queryRunner.query(`DROP TYPE "public"."devices_connectiontype_enum"`);
        await queryRunner.query(`DROP TYPE "public"."devices_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."devices_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_49ee2f991fefeedef715fa3b61"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_419857fc68975b6df572ad288d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_55e6651198104efea0b04568a8"`);
        await queryRunner.query(`DROP TABLE "schedules"`);
        await queryRunner.query(`DROP TYPE "public"."schedules_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e956cdd092501b3c2dbdfcd174"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e7e6185b1ee83be55370972627"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a1b16acf6c41ce6da45612c4a9"`);
        await queryRunner.query(`DROP TABLE "scripts"`);
        await queryRunner.query(`DROP TYPE "public"."scripts_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fef990ce4738f381fbf08dd32b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2e688a3ebb477d286c7d3177de"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9d4dac50fa63e9b6c5cccc14bd"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a8aded2f90f448876f7fe63eab"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4c8ddcaa09bb1ac50dbbe8120c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f51f54e33eac0d4d7ada7422cf"`);
        await queryRunner.query(`DROP TABLE "shares"`);
        await queryRunner.query(`DROP TYPE "public"."shares_accesslevel_enum"`);
        await queryRunner.query(`DROP TYPE "public"."shares_sharetype_enum"`);
        await queryRunner.query(`DROP TYPE "public"."shares_resourcetype_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9c01268558440182b9888652e2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_dc9a46466e27a2e969f760d083"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9cde4c8a4997ea781cdb5af3ec"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a69a9338732daa77803f7ec450"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_70aae5590b03f9a19850ea429f"`);
        await queryRunner.query(`DROP TABLE "solution_templates"`);
        await queryRunner.query(`DROP TYPE "public"."solution_templates_category_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c59559e7872bc9726adef4669f"`);
        await queryRunner.query(`DROP TABLE "tenants"`);
        await queryRunner.query(`DROP TYPE "public"."tenants_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fb71b94617998eb1e04f87d14d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1527965b6fd30f017a4f8affbc"`);
        await queryRunner.query(`DROP TABLE "widget_bundles"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ceebe2fe995d01aeff8cb013f5"`);
        await queryRunner.query(`DROP TABLE "two_factor_auth"`);
        await queryRunner.query(`DROP TYPE "public"."two_factor_auth_method_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_97672ac88f789774dd47f7c8be"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "public"."users_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."users_role_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6d8daed2fa8cd92bb62d9b4255"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e6f81a5fb5bd325c2316ec630b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_077460328e63732c0d5bae1582"`);
        await queryRunner.query(`DROP TABLE "widget_types"`);
        await queryRunner.query(`DROP TYPE "public"."widget_types_category_enum"`);
    }

}
