export enum AuditAction {
  CREATE = 'create',
  READ = 'read',
  UPDATE = 'update',
  DELETE = 'delete',
  ACTIVATE = 'activate',
  DEACTIVATE = 'deactivate',
  LOGIN = 'login',
  LOGOUT = 'logout',
  LOGIN_FAILED = 'login_failed',
  PASSWORD_CHANGE = 'password_change',
  PASSWORD_RESET = 'password_reset',
  EMAIL_VERIFY = 'email_verify',
  STATUS_CHANGE = 'status_change',
  ROLE_CHANGE = 'role_change',
  PERMISSION_CHANGE = 'permission_change',
  DEVICE_CONNECT = 'device_connect',
  DEVICE_DISCONNECT = 'device_disconnect',
  DEVICE_COMMAND = 'device_command',
  ALARM_CREATE = 'alarm_create',
  ALARM_UPDATE = 'alarm_update',
  ALARM_ACKNOWLEDGE = 'alarm_acknowledge',
  ALARM_CLEAR = 'alarm_clear',
  NOTIFICATION_SENT = 'notification_sent',
  FILE_UPLOAD = 'file_upload',
  FILE_DELETE = 'file_delete',
  SETTINGS_CHANGE = 'settings_change',
  API_KEY_CREATE = 'api_key_create',
  API_KEY_REVOKE = 'api_key_revoke',
  SUBSCRIPTION_CREATE = 'subscription_create',
  SUBSCRIPTION_UPDATE = 'subscription_update',
  SUBSCRIPTION_CANCEL = 'subscription_cancel',
  PAYMENT_SUCCESS = 'payment_success',
  PAYMENT_FAILED = 'payment_failed',
  ALARM_TRIGGER = 'alarm_trigger',
}

export enum AuditEntityType {
  USER = 'user',
  TENANT = 'tenant',
  CUSTOMER = 'customer',
  DEVICE = 'device',
  DEVICE_PROFILE = 'device_profile',
  ASSET = 'asset',
  ALARM = 'alarm',
  NOTIFICATION = 'notification',
  DASHBOARD = 'dashboard',
  TELEMETRY = 'telemetry',
  RULE_CHAIN = 'rule_chain',
  RULE_NODE = 'rule_node',
  SETTINGS = 'settings',
  FILE = 'file',
  API_KEY = 'api_key',
  SUBSCRIPTION = 'subscription',
  PAYMENT = 'payment',
  WIDGET = 'widget',
  INTEGRATION = 'integration',
}

export enum AuditSeverity {
  INFO = 'info',
  WARNING = 'warning',
  ERROR = 'error',
  CRITICAL = 'critical',
}
